version: "3"
services:
  app:
    image: tupi4ok/post_image:latest
    depends_on:
      - mongo
    ports:
      - "5000:5000"
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_URI: mongodb://root:example@mongo:27017/Prod_db?authSource=admin
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data: