version: "3"
services:
  app:
    image: tupi4ok/post_image:latest
    depends_on:
      - db
    ports:
      - "5000:5000"
    environment:
      SPRING_PROFILES_ACTIVE: production
      DB_URI: mongodb://localhost:27017/Dev_db
  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodata:/var/lib/mongo/data
volumes:
  mongodata: