name: CI/CD with Docker

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: "development"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Make Gradlew executable
        run: chmod +x ${{github.workspace}}/app/gradlew
        working-directory: app
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
          build-root-directory: app
  docker_push:
    runs-on: ubuntu-latest
    env:
      SPRING_PROFILES_ACTIVE: "development"
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

    - name: Build and push Docker image
      run: |
        docker build -t tupi4ok/post_image:latest .
        docker push tupi4ok/post_image:latest
      working-directory: postal_items
